---
title: "multi_analysis"
author: '700037484'
date: "`r Sys.Date()`"
output: html_document
---
`r #For harry: error library(showtext) does not exist, instead using library(sysfonts)`
`r #requires bb_init_analysis.Rmd`

``` {r GLOBAL VARS}
PATH_VALUEREPORTINGTABLE_HBA1C_OBSERVATIONAL = "file-#" # UKbb-hosted value reporting table from observational HbA1c logistic regression
PATH_VALUEREPORTINGTABLE_HBA1C_GLYCAEMIC = "file-#" # UKbb-hosted value reporting table from causal glycaemic HbA1c logistic regression
PATH_VALUEREPORTINGTABLE_HBA1C_NONGLYC = "file-#" # UKbb-hosted value reporting table from causal non-glyc HbA1c logistic regression

PATH_VALUEREPORTINGTABLE_BMI_OBSERVATIONAL = "file-#" # UKbb-hosted value reporting table from observational BMI logistic regression
PATH_VALUEREPORTINGTABLE_BMI_CAUSAL = "file-#" # UKbb-hosted value reporting table from causal BMI logistic regression
```

``` {r Harry's code to create Exeter-themed plots}
#> Code taken from Harry Green's GitHub: source_url("https://raw.githubusercontent.com/hdg204/exeteR/main/ex_theme.R")

#define exeter colours
ex_night_green='#022020'
ex_dark_green='#003c3c'
ex_deep_green='#007d69'
ex_rich_green='#00a87e'
ex_bright_green='#00c896'
ex_highlight_green='#00dca5'

ex_wood_brown='#93272c'
ex_tree_brown='#b46a55'
ex_rose_red='#e60000'
ex_warm_red='#f9423a'
ex_pure_purple='#702081'
ex_low_purple='#9569be'
ex_coral_orange='#fc4c02'
ex_peach='#ff7f41'
ex_hay='#ffc62c'
ex_sun_yellow='#f3d54e'
ex_deep_sea='#250e62'
ex_morning_sky='#6ab3e7'
ex_sunset_pink='#e78699'
ex_light_pink='#f4c3cd'
ex_stone_grey='#898b8d'


exeter_full_palette=c(ex_dark_green,ex_deep_green,ex_highlight_green,ex_wood_brown,ex_pure_purple,ex_deep_sea,ex_sun_yellow,ex_low_purple,ex_sunset_pink,ex_morning_sky,ex_hay,ex_rose_red)
exeter_greens=c(ex_dark_green,ex_deep_green,ex_highlight_green) 
exeter_palette=c(ex_dark_green,ex_deep_green,ex_highlight_green,ex_wood_brown,ex_sun_yellow)

font_add_google(name = "Outfit", family = "Outfit") # threw error! use  sysfonts instead which works!
wt <- seq(100, 900, 100)
purrr::walk(
  wt,
  \(x) font_add_google(
    name = "Outfit",
    family = paste0("Outfit", x),
    regular.wt = x
  )
)

ex_dark_theme=theme_bw()+
    theme(text = element_text(family = "Outfit200",size = 10,colour='#FFFFFF'),
        axis.line = element_line(colour = "#FFFFFF"),
        panel.grid.minor = element_blank(),
        panel.background = element_rect(fill = ex_dark_green,colour='#FFFFFF'),
		plot.background = element_rect(fill = ex_dark_green,colour=ex_dark_green),
        plot.title = element_text(hjust = 0.5,family="Outfit700",color=ex_highlight_green),
		axis.text.x = element_text(color="#FFFFFF"),
        axis.text.y = element_text(color="#FFFFFF"),
		panel.grid.major = element_line(size = 0.25),
		panel.border = element_rect(color = "#FFFFFF", fill = NA),
		strip.background =element_rect(fill=ex_dark_green,color='#FFFFFF'),
		strip.text = element_text(colour = '#FFFFFF',family = "Outfit"),
		axis.line.x=element_line(colour="#FFFFFF"),
		axis.line.y=element_line(colour="#FFFFFF"),
		axis.ticks=element_line(colour="#FFFFFF"))
```

``` {r HbA1c multi-model forestplot}
#> --------------------- Load in HbA1c data -------------------------------- <#

#> Load in .csv files by IDs
system(paste0('dx download ', PATH_VALUEREPORTINGTABLE_HBA1C_OBSERVATIONAL)) # observational
system(paste0('dx download ', PATH_VALUEREPORTINGTABLE_HBA1C_GLYCAEMIC)) # Glycaemic
system(paste0('dx download ', PATH_VALUEREPORTINGTABLE_HBA1C_NONGLYC)) # Non-Glyc


#> Array of Model names for assignment and ordering
model_order = c("HbA1c Observational", "Glycaemic HbA1c MR", "Non-glycaemic HbA1c MR")

#> Read in data to dataframe
forestplot_data = read.csv("ObsvAssoc_logreg_HBA1C_values.csv") %>%
  mutate(model = factor(model_order[1])) %>%
  rbind(
    read.csv("MR_GLYC_HBA1C_logreg_pvalues.csv") %>%
      mutate(model = factor(model_order[2])),
    read.csv("MR_NONGLYC_HBA1C_logreg_pvalues.csv") %>%
      mutate(model = factor(model_order[3]))
  ) %>%
  mutate( # exponentiate coefficients and CI
    coef = exp(Coef_logit),
    lCI = exp(Lower_CI),
    uCI = exp(Upper_CI)
  )
	
#> --------------------- EXETER-THEMED GRAPH Version1 -------------------------------- <#
graph_allforestplot = ggplot(
  forestplot_data %>%
    mutate(
      Origin = factor(Origin, levels = rev(c("Bacterial", "Fungal", "Viral")))
    ),
   aes(x = coef, y = Origin)
)+
  geom_vline(xintercept = 1,colour='red') +
  geom_point(colour=ex_highlight_green,size=2) +
  geom_errorbarh(aes(xmin = lCI, xmax = uCI),colour=ex_highlight_green,linewidth=1) +
  facet_wrap(~ model, ncol = 1) +
  theme_minimal() +
  xlab("Odds Ratio per 1 HbA1c (mmol/mol) increase") +
  labs(title = "Investigating HbA1c as a causal risk factor of infections") +
  scale_color_manual(values = exeter_full_palette) +
  scale_fill_manual(values = exeter_full_palette) +
  ex_dark_theme +
  theme(axis.title.y=element_blank()) # remove Harry's Y axis text pulled from colname ('Origin')
                               

#> --------------------- EXETER-THEMED GRAPH Version2-------------------------------- <#
graph_allforestplot = ggplot(
  forestplot_data %>%
    mutate(
      model = factor(model, levels = rev(model_order)),
      Origin = factor(Origin, levels = rev(c("Bacterial", "Fungal", "Viral")))
    ),
  aes(x = coef, xmin = lCI, xmax = uCI, y = model, colour = Origin)
) +
  geom_vline(xintercept = 1, color = "red", size = 0.25) +  # Add a vertical line indicating no significance
  geom_point(size = 3, position=position_dodge(width=0.5)) +
  geom_errorbarh(height = 0.1,  position=position_dodge(width=0.5)) +
  labs(x = "Odds Increase per 1 HbA1c (mmol/mol) increase", y = NULL) +
  scale_colour_brewer(palette = "Dark2") +
  xlim(c(0.9, 1.2)) +
  guides(colour = guide_legend(
    override.aes = list(size=1),
    reverse = TRUE,
    title = "Infection"
  )) +
  theme(
    text = element_text(size=10),
    legend.text=element_text(size=8),
    axis.text.x=element_text(colour="red"),
    axis.text.y=element_text(colour="red"),
    panel.background = element_rect(fill = 'lightblue', color = 'purple'),
    panel.grid.major = element_line(color = 'red', linetype = 'dotted'),
    panel.grid.minor = element_line(color = 'green', size = 2)
  )


#> --------------------- NON-EXETER-THEMED GRAPH Version1-------------------------------- <#
# Unsure what the difference visually is between these two
graph_allforestplot = ggplot(
  forestplot_data %>%
    mutate(
      Origin = factor(Origin, levels = rev(c("Bacterial", "Fungal", "Viral")))
    ),
  aes(x = coef, y = Origin, colour = Origin)
)+
  geom_vline(xintercept = 1,colour='red') +
  geom_point(size=2) +
  geom_errorbarh(aes(xmin = lCI, xmax = uCI),linewidth=0.8) +
  facet_wrap(~ model, ncol = 1) +
  theme_minimal() +
  xlab("Odds Ratio per 1 HbA1c (mmol/mol) increase") +
  labs(title = "Investigating HbA1c as a causal risk factor of infections") +
  theme(
    axis.title.y=element_blank(), # remove Harry's Y axis text pulled from colname ('Origin')
    legend.position = "none" # remove legend
  )

#> --------------------- NON-EXETER-THEMED GRAPH Version2-------------------------------- <#
graph_allforestplot = ggplot(
  forestplot_data %>%
    mutate(
      model = factor(model, levels = rev(model_order)),
      Origin = factor(Origin, levels = rev(c("Bacterial", "Fungal", "Viral")))
    ),
  aes(x = coef, xmin = lCI, xmax = uCI, y = model, colour = Origin)
) +
  geom_vline(xintercept = 1, color = "red", size = 0.25) +  # Add a vertical line indicating no significance
  geom_point(size = 3, position=position_dodge(width=0.5)) +
  geom_errorbarh(height = 0.1,  position=position_dodge(width=0.5)) +
  labs(x = "Odds Increase per 1 HbA1c (mmol/mol) increase", y = NULL) +
  scale_colour_brewer(palette = "Dark2") +
  xlim(c(0.9, 1.3)) +
  guides(colour = guide_legend(
    override.aes = list(size=1),
    reverse = TRUE,
    title = "Infection"
  )) +
  theme(
    text = element_text(size=10),
    legend.text=element_text(size=8)
  )



#> --------------------- SAVE INTO /SAVEABLES/ -------------------------------- <#
#> Saving
ggsave(
  plot = graph_allforestplot,
  paste0("saveables/graphs/summary_forestplot.png"),
  width = 7,
  height = 4.5,
  dpi = 600
)

```

``` {r BMI multi-model forestplot}
#> --------------------- Load in BMI data -------------------------------- <#

system(paste0('dx download ', PATH_VALUEREPORTINGTABLE_BMI_OBSERVATIONAL)) # observational
system(paste0('dx download ', PATH_VALUEREPORTINGTABLE_BMI_CAUSAL)) # MR-data

#> Array of Model names for assignment and ordering
model_order = c("BMI\nObservational", "BMI MR")

forestplot_bmi_data = read.csv("ObsvAssoc_logreg_BMI_values.csv") %>%
  mutate(model = factor(model_order[1])) %>%
  rbind(
    read.csv("MR_BMI_logreg_pvalues.csv") %>%
      mutate(model = factor(model_order[2]))
  ) %>%
  mutate( # exponentiate coefficients and CI
    coef = exp(Coef_logit),
    lCI = exp(Lower_CI),
    uCI = exp(Upper_CI)
  )

#> --------------------- EXETER-THEMED BMI GRAPH-------------------------------- <#
graph_bmi_foresplot = ggplot(
  forestplot_bmi_data %>%
    mutate(
      Origin = factor(Origin, levels = rev(c("Bacterial", "Fungal", "Viral")))
    ),
   aes(x = coef, y = Origin)
)+
  geom_vline(xintercept = 1,colour='red') +
  geom_point(colour=ex_highlight_green,size=2) +
  geom_errorbarh(aes(xmin = lCI, xmax = uCI),colour=ex_highlight_green,linewidth=1) +
  facet_wrap(~ model, ncol = 1) +
  theme_minimal() +
  xlab("Odds Ratio per 1 BMI (m kg^-2) increase") +
  labs(title = "Investigating BMI as a causal risk factor of infections") +
  scale_color_manual(values = exeter_full_palette) +
  scale_fill_manual(values = exeter_full_palette) +
  ex_dark_theme +
  theme(axis.title.y=element_blank()) # remove Harry's Y axis text pulled from colname ('Origin')
                               


#> --------------------- NON-EXETER-THEMED BMI GRAPH VERSION-------------------------------- <#

graph_bmi_foresplot = ggplot(
  forestplot_bmi_data %>%
    mutate(
      Origin = factor(Origin, levels = rev(c("Bacterial", "Fungal", "Viral")))
    ),
   aes(x = coef, y = Origin, color = Origin)
)+
  geom_vline(xintercept = 1,colour='red') +
  geom_point(size=2) +
  geom_errorbarh(aes(xmin = lCI, xmax = uCI),linewidth=0.8) +
  facet_wrap(~ model, ncol = 1) +
  theme_minimal() +
  xlab("Odds Ratio per 1 BMI (kg/m2) increase") +
  labs(title = "Investigating BMI as a causal risk factor of infections") +
  theme(
    axis.title.y=element_blank(), # remove Harry's Y axis text pulled from colname ('Origin')
    legend.position = "none" # remove legend
  )


#> --------------------- SAVE INTO /SAVEABLES/ -------------------------------- <#
#> Saving
ggsave(
  plot = graph_bmi_foresplot,
  paste0("saveables/graphs/summary_BMI_forestplot.png"),
  width = 7,
  height = 4.5,
  dpi = 600
)

```